/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.umo.dc.forum;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import lk.umo.dc.domain.model.Comment;
import lk.umo.dc.messaging.broadcast.CommentBroadCastUtil;
import lk.umo.dc.sevice.CommentRatingService;
import javax.swing.JOptionPane;
import lk.umo.dc.util.DBConnection;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class CommentPanel extends javax.swing.JPanel {

    private Comment comment;
    private CommentBroadCastUtil commentBroadCastUtil = new CommentBroadCastUtil();

    private static final String INSERT_COMENT_RATING = "INSERT INTO comment_rating (comment_id, node, rating) values (?, ?, ?)";
    private static final String SELECT_FILE_RATING = "SELECT * FROM comment_rating WHERE comment_id = ?";

    /**
     * Creates new form CommentPanel
     */
    public CommentPanel(Comment comment) {
        this.comment = comment;
        initComponents();

        txtCmnt.setText(comment.getComment());
        int updatedRating = getCommentRating(comment.getCommentId())[0];
        int ratingCount = getCommentRating(comment.getCommentId())[1];
        lblCmntRating.setText(updatedRating + " out of " + ratingCount + " ratings");
    }

    public void saveCommentRating(String commentId, String node, int rating) {
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(INSERT_COMENT_RATING);
            pstmt.setString(1, commentId);
            pstmt.setString(2, node);
            pstmt.setInt(3, rating);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println("save comment rating : " + e);
        }
    }

    public int[] getCommentRating(String commentId) {
        int rating = 0;
        int count = 0;
        int ratingSum = 0;

        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(SELECT_FILE_RATING);
            pstmt.setString(1, commentId);
            ResultSet rs = pstmt.executeQuery();

            // loop through the result set
            System.out.println(rs);
            while (rs.next()) {
                count = count + 1;
                ratingSum = ratingSum + rs.getInt("rating");
                rating = ratingSum / (count);
            }
        } catch (SQLException e) {
            System.out.println("get comment rating : " + e);
        }
        return new int[]{rating, count};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupCommentRating = new javax.swing.ButtonGroup();
        btnRateCmnt = new javax.swing.JButton();
        lblCmntRating = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCmnt = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        CommentRate2 = new javax.swing.JRadioButton();
        CommentRate1 = new javax.swing.JRadioButton();
        CommentRate4 = new javax.swing.JRadioButton();
        CommentRate3 = new javax.swing.JRadioButton();
        CommentRate5 = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(560, 114));

        btnRateCmnt.setText("Rate");
        btnRateCmnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRateCmntActionPerformed(evt);
            }
        });

        txtCmnt.setEditable(false);
        txtCmnt.setColumns(20);
        txtCmnt.setRows(5);
        txtCmnt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtCmnt);

        jLabel3.setText("☆");

        CommentRate2.setText("2");
        CommentRate2.setActionCommand("2"); groupCommentRating.add(CommentRate2);

        CommentRate1.setText("1");
        CommentRate1.setActionCommand("1"); groupCommentRating.add(CommentRate1);

        CommentRate4.setText("4");
        CommentRate4.setActionCommand("4"); groupCommentRating.add(CommentRate4);

        CommentRate3.setText("3");
        CommentRate3.setActionCommand("3"); groupCommentRating.add(CommentRate3);

        CommentRate5.setText("5");
        CommentRate5.setActionCommand("5"); groupCommentRating.add(CommentRate5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCmntRating, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(CommentRate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentRate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CommentRate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentRate4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentRate5)
                .addGap(18, 18, 18)
                .addComponent(btnRateCmnt, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRateCmnt)
                        .addComponent(jLabel3)
                        .addComponent(CommentRate2)
                        .addComponent(CommentRate4)
                        .addComponent(CommentRate5)
                        .addComponent(CommentRate3)
                        .addComponent(CommentRate1))
                    .addComponent(lblCmntRating, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRateCmntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRateCmntActionPerformed
        int rate=0;
        try{
        rate = Integer.valueOf(groupCommentRating.getSelection().getActionCommand());
        }catch(Exception e){
            
        }
        if (rate == 0) {
            JOptionPane.showMessageDialog(btnRateCmnt, "Please select rating","Forum", 2);
        } else {
            saveCommentRating(comment.getCommentId(), comment.getNode(), rate);
            int updatedRating = getCommentRating(comment.getCommentId())[0];
            int ratingCount = getCommentRating(comment.getCommentId())[1];
            lblCmntRating.setText(updatedRating + " out of " + ratingCount + " ratings");
            JOptionPane.showMessageDialog(btnRateCmnt, "Rating submitted!","Forum", 1);
            commentBroadCastUtil.broadcastCommentRating(comment.getCommentId(), comment.getNode(), rate);
        }
    }//GEN-LAST:event_btnRateCmntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CommentRate1;
    private javax.swing.JRadioButton CommentRate2;
    private javax.swing.JRadioButton CommentRate3;
    private javax.swing.JRadioButton CommentRate4;
    private javax.swing.JRadioButton CommentRate5;
    private javax.swing.JButton btnRateCmnt;
    private javax.swing.ButtonGroup groupCommentRating;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCmntRating;
    private javax.swing.JTextArea txtCmnt;
    // End of variables declaration//GEN-END:variables
}
