/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.umo.dc.forum;

import lk.umo.dc.config.NodeContext;
import lk.umo.dc.domain.model.Comment;
import lk.umo.dc.messaging.broadcast.CommentBroadCastUtil;
import lk.umo.dc.sevice.CommentService;
import lk.umo.dc.sevice.FileRatingService;
import lk.umo.dc.util.Utils;
import java.awt.GridBagConstraints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.swing.JOptionPane;
import lk.umo.dc.util.DBConnection;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Forum extends javax.swing.JFrame {

    private CommentService commentService = new CommentService();
    private CommentBroadCastUtil broadCastUtil = new CommentBroadCastUtil();
    private String fileName;
    
    private static final Logger LOGGER = LogManager.getLogger(FileRatingService.class.getName());

    private static final String INSERT_FILE_RATING = "INSERT INTO file_rating (file_hash, node, rating) values (?, ?, ?)";
    private static final String SELECT_FILE_RATING = "SELECT * FROM file_rating WHERE file_hash = ?";
    /**
     * Creates new form Forum
     */
    public Forum() {
        initComponents();
    }
    
    public Forum(String fileName) {
        this.fileName = fileName;
        initComponents();
        lblFileName.setText(fileName);
        
        int rating = getFileRating(Utils.md5(fileName))[0];
        int rateCount = getFileRating(Utils.md5(fileName))[1];
        lblFileRating.setText(rating + " out of " + rateCount + " ratings");
        
        loadComments();
    }
    
    public void saveFileRating(String fileHash, String node, int rating){
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(INSERT_FILE_RATING);
            pstmt.setString(1, fileHash);
            pstmt.setString(2, node);
            pstmt.setInt(3, rating);
            pstmt.executeUpdate();
        } catch (SQLException e) {
            System.out.println("save file rating:"+ e);
        }
    }
    
    public int[] getFileRating(String fileHash){
        int rating = 0;
        int count = 0;
        int ratingSum = 0;

        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(SELECT_FILE_RATING);
            pstmt.setString(1, fileHash);
            ResultSet rs    = pstmt.executeQuery();

            // loop through the result set
            while (rs.next()) {
                count = count + 1;
                ratingSum = ratingSum +rs.getInt("rating");
                rating = ratingSum / (count);
            }
        } catch (SQLException e) {
            System.out.println("get file rating"+ e);
        }
        return new int[] {rating, count};
    }
    
    private void loadComments(){
        cmntPnlsList.removeAll();
        List<Comment> commentsList = commentService.getComments(Utils.md5(fileName));
        int cmntCount = 0;
        for (Comment comment : commentsList) {
            CommentPanel commentPanel = new CommentPanel(comment);
            GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = cmntCount;
            cmntPnlsList.add(commentPanel, gridBagConstraints);
            cmntCount = cmntCount + 1;
        }
        cmntPnlsList.repaint();
        cmntPnlsList.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupfileRatings = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCmnt = new javax.swing.JTextArea();
        btnCmntSubmit = new javax.swing.JButton();
        jscrlCmnts = new javax.swing.JScrollPane();
        cmntPnlsList = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        fileR1 = new javax.swing.JRadioButton();
        fileR2 = new javax.swing.JRadioButton();
        fileR3 = new javax.swing.JRadioButton();
        fileR4 = new javax.swing.JRadioButton();
        fileR5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblFileRating = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Forum");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        txtCmnt.setColumns(20);
        txtCmnt.setRows(5);
        jScrollPane1.setViewportView(txtCmnt);

        btnCmntSubmit.setText("Submit Comment");
        btnCmntSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCmntSubmitActionPerformed(evt);
            }
        });

        cmntPnlsList.setMaximumSize(new java.awt.Dimension(566, 32767));
        cmntPnlsList.setLayout(new java.awt.GridBagLayout());
        jscrlCmnts.setViewportView(cmntPnlsList);

        groupfileRatings.add(fileR1);
        fileR1.setText("1");
        fileR1.setActionCommand("1");
        groupfileRatings.add(fileR1);

        fileR2.setText("2");
        fileR2.setActionCommand("2");
        groupfileRatings.add(fileR2);

        fileR3.setText("3");
        fileR3.setActionCommand("3");
        groupfileRatings.add(fileR3);

        fileR4.setText("4");
        fileR4.setActionCommand("4");
        groupfileRatings.add(fileR4);

        fileR5.setText("5");
        fileR5.setActionCommand("5");
        groupfileRatings.add(fileR5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileR3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fileR4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileR5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileR1)
                    .addComponent(fileR2)
                    .addComponent(fileR3)
                    .addComponent(fileR4)
                    .addComponent(fileR5)))
        );

        jButton1.setText("Rate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscrlCmnts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFileRating, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCmntSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btnCmntSubmit)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jscrlCmnts, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFileRating, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );

        jLabel2.setText("File name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCmntSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCmntSubmitActionPerformed
        if (txtCmnt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Comment is empty!","Forum",2);
        } else {
            
            Comment comment = new Comment(UUID.randomUUID().toString(), Utils.md5(fileName),
                    NodeContext.getUserName(), txtCmnt.getText(), new Date());
            commentService.saveComment(comment);
            
            JOptionPane.showMessageDialog(rootPane, "Comment submitted", "Forum", 1);
            broadCastUtil.broadcastComment(comment);
            loadComments();
        }
    }//GEN-LAST:event_btnCmntSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(groupfileRatings.getSelection() != null) {
            int rating = Integer.valueOf(groupfileRatings.getSelection().getActionCommand());
            
            saveFileRating(Utils.md5(fileName), NodeContext.getUserName(), rating);
            
            JOptionPane.showMessageDialog(rootPane, "Ratings submitted","Forum",1);
            
            int updatedRating = getFileRating(Utils.md5(fileName))[0];
            int rateCount = getFileRating(Utils.md5(fileName))[1];
            lblFileRating.setText(updatedRating + " out of " + rateCount + " ratings");
            broadCastUtil.broadcastFileRating(Utils.md5(fileName), NodeContext.getUserName(), rating);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please select rating","Forum", 2);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCmntSubmit;
    private javax.swing.JPanel cmntPnlsList;
    private javax.swing.JRadioButton fileR1;
    private javax.swing.JRadioButton fileR2;
    private javax.swing.JRadioButton fileR3;
    private javax.swing.JRadioButton fileR4;
    private javax.swing.JRadioButton fileR5;
    private javax.swing.ButtonGroup groupfileRatings;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jscrlCmnts;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblFileRating;
    private javax.swing.JTextArea txtCmnt;
    // End of variables declaration//GEN-END:variables
}
